### ISSUE TITLE
SOI: BIT, AIT, BLC, ALC Combined Map Checklist

### ISSUE THREAD

**Issue by Robot-Panda15** [7Cav/7thCavalry_Training_Missions#29]
Build these features on separate maps first, using the same training areas for AIT, BLC, and ALC. Merge when done.
BIT:
- [x] Pull Current BIT Map from SFC Whitsel
- [x] Utilize specific class names for students and instructors to work with intended markers
- [x] Ensure OPFOR, INDEP, and BLUFOR HUD icons for instructors ([initPlayerLocal.sqf](https://pastebin.com/Fi6EmM1g))
- [ ] Function Test
- [ ] Merge into "SOI_INF_1" mission file

AIT: 
- [ ] Utilize features present in BIT file for AIT file, modify for AIT purposes
- [ ] Install Slide Shows
- [x] Utilize specific class names for students and instructors to work with intended markers
- [x] Ensure OPFOR, INDEP, and BLUFOR HUD icons for instructors ([initPlayerLocal.sqf](https://pastebin.com/Fi6EmM1g))
- [ ] Function Test
- [ ] Merge into "SOI_INF_1" mission file

BLC:
- [ ] Utilize features present in AIT file, modify for BLC purposes
- [ ] Install Slide Shows
- [ ] Use AIT FTXs
- [x] Utilize specific class names for students and instructors to work with intended markers
- [x] Ensure OPFOR, INDEP, and BLUFOR HUD icons for instructors ([initPlayerLocal.sqf](https://pastebin.com/Fi6EmM1g))
- [ ] Function Test
- [ ] Merge into "SOI_INF_1" mission file

ALC:
- [ ] Utilize features present in BLC file, modify for ALC purposes
- [ ] Install Slide Shows
- [ ] Use AIT/BLC FTXs, modify for ALC purposes
- [x] Utilize specific class names for students and instructors to work with intended markers
- [x] Ensure OPFOR, INDEP, and BLUFOR HUD icons for instructors ([initPlayerLocal.sqf](https://pastebin.com/Fi6EmM1g))
- [ ] Function Test
- [ ] Merge into "SOI_INF_1" mission file

School of Infantry Training Map
- [ ] Cleanup scripts
- [ ] Ensure different class names for different course slots
- [ ] Function Test
- [ ] Push to S3 SOI Lead, Training Lead, and HQ for review and approval

**Comment by longlostblake** [comment]
For ease i would recomend we don't combine all four but do combine them into pairs. There would be a lot of extra edits to make to allow us to easily update them in the future.
I propose we pair:
- BIT & AIT 
- BLC & ALC

Doing it this way means way less cScripts updates and allows us to stay on the main branch for future updates & ease of life :)

**Comment by Robot-Panda15** [comment]
Combining all four is mostly due to the fact that they use the same FTXs. Not sure what you mean by less cScripts updates though, as having two separate files compared to one would mean more?

**Comment by longlostblake** [comment]
Think of cScripts as a seperate entity you copy over once you've made your mission (although not technically true).

**Step A:** Each S3 Class requires a unit class name for hidden markers (so 4 serperate unit types, one per class)
**Step B:** Currently we only have 2 cScripts Classes set up for S3 training, which set loadouts, permissions, invincibility etc.  (so currently we have only two classnames can be chosen from for Step A.)

I haven't had chance to look at the BLC or ALC map yet but it may be possible to combine all three like you say, providing they have the same FTX's and if 'hidden markers' are not 100% required.

Currently, i have merged the BIT & AIT and have a really stable result which i'd like to go over with you.

**Comment by longlostblake** [comment]
@Robot-Panda15 Are you able to start working on just the practical side of things? Don't worry too much about the markers being assigned, players being placed or HQ being built, just yet try to get a foundation of practicals we can provide.

**Comment by Robot-Panda15** [comment]
I need to grab the BIT file from Whitsel first in order to get cracking on it

**Comment by longlostblake** [comment]
Alright, try to grab a hold of it and send me a copy  :)

**Comment by longlostblake** [comment]
Fixed FTX 4 & FTX 5's non-synced triggers for waypoints if we intend to use.

**Comment by longlostblake** [comment]
On hold

**Comment by longlostblake** [comment]
Not viable with current cScripts/Mission configs.
